// File: mux_wrapper.v
// Generated by MyHDL 0.7
// Date: Mon Nov 28 10:08:42 2011


`timescale 1ns/10ps

module mux_wrapper (
    select,
    data_in,
    data_out
);


output select;
wire select;
output data_in;
wire data_in;
output data_out;
wire data_out;







   mux
   #(
      .ARCHITECTURE ("BEHAVIORAL"),
      .SELECT_LINES (8)
   ) mux_mux1 (
      .select   (select),
      .data_in  (data_in),
      .data_out (data_out)
   );
   
endmodule
